name: Snyk Maven Scan

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - run: |
        curl -sL https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x snyk && sudo mv snyk /usr/local/bin/
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test --all-projects
